# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lukewen/PCL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lukewen/PCL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukewen/PCL/CMakeFiles /home/lukewen/PCL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukewen/PCL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named concatenate

# Build rule for target.
concatenate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 concatenate
.PHONY : concatenate

# fast build rule for target.
concatenate/fast:
	$(MAKE) -f CMakeFiles/concatenate.dir/build.make CMakeFiles/concatenate.dir/build
.PHONY : concatenate/fast

#=============================================================================
# Target rules for targets named extract_indices

# Build rule for target.
extract_indices: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extract_indices
.PHONY : extract_indices

# fast build rule for target.
extract_indices/fast:
	$(MAKE) -f CMakeFiles/extract_indices.dir/build.make CMakeFiles/extract_indices.dir/build
.PHONY : extract_indices/fast

#=============================================================================
# Target rules for targets named kdtree_search

# Build rule for target.
kdtree_search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kdtree_search
.PHONY : kdtree_search

# fast build rule for target.
kdtree_search/fast:
	$(MAKE) -f CMakeFiles/kdtree_search.dir/build.make CMakeFiles/kdtree_search.dir/build
.PHONY : kdtree_search/fast

#=============================================================================
# Target rules for targets named matrix_transform

# Build rule for target.
matrix_transform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_transform
.PHONY : matrix_transform

# fast build rule for target.
matrix_transform/fast:
	$(MAKE) -f CMakeFiles/matrix_transform.dir/build.make CMakeFiles/matrix_transform.dir/build
.PHONY : matrix_transform/fast

#=============================================================================
# Target rules for targets named narf_feature_extraction

# Build rule for target.
narf_feature_extraction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 narf_feature_extraction
.PHONY : narf_feature_extraction

# fast build rule for target.
narf_feature_extraction/fast:
	$(MAKE) -f CMakeFiles/narf_feature_extraction.dir/build.make CMakeFiles/narf_feature_extraction.dir/build
.PHONY : narf_feature_extraction/fast

#=============================================================================
# Target rules for targets named normal_estimation

# Build rule for target.
normal_estimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 normal_estimation
.PHONY : normal_estimation

# fast build rule for target.
normal_estimation/fast:
	$(MAKE) -f CMakeFiles/normal_estimation.dir/build.make CMakeFiles/normal_estimation.dir/build
.PHONY : normal_estimation/fast

#=============================================================================
# Target rules for targets named octree_change_detection

# Build rule for target.
octree_change_detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 octree_change_detection
.PHONY : octree_change_detection

# fast build rule for target.
octree_change_detection/fast:
	$(MAKE) -f CMakeFiles/octree_change_detection.dir/build.make CMakeFiles/octree_change_detection.dir/build
.PHONY : octree_change_detection/fast

#=============================================================================
# Target rules for targets named octree_search

# Build rule for target.
octree_search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 octree_search
.PHONY : octree_search

# fast build rule for target.
octree_search/fast:
	$(MAKE) -f CMakeFiles/octree_search.dir/build.make CMakeFiles/octree_search.dir/build
.PHONY : octree_search/fast

#=============================================================================
# Target rules for targets named passthrough

# Build rule for target.
passthrough: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 passthrough
.PHONY : passthrough

# fast build rule for target.
passthrough/fast:
	$(MAKE) -f CMakeFiles/passthrough.dir/build.make CMakeFiles/passthrough.dir/build
.PHONY : passthrough/fast

#=============================================================================
# Target rules for targets named pcd_write

# Build rule for target.
pcd_write: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcd_write
.PHONY : pcd_write

# fast build rule for target.
pcd_write/fast:
	$(MAKE) -f CMakeFiles/pcd_write.dir/build.make CMakeFiles/pcd_write.dir/build
.PHONY : pcd_write/fast

#=============================================================================
# Target rules for targets named project_inliers

# Build rule for target.
project_inliers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project_inliers
.PHONY : project_inliers

# fast build rule for target.
project_inliers/fast:
	$(MAKE) -f CMakeFiles/project_inliers.dir/build.make CMakeFiles/project_inliers.dir/build
.PHONY : project_inliers/fast

#=============================================================================
# Target rules for targets named range_image_creation

# Build rule for target.
range_image_creation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 range_image_creation
.PHONY : range_image_creation

# fast build rule for target.
range_image_creation/fast:
	$(MAKE) -f CMakeFiles/range_image_creation.dir/build.make CMakeFiles/range_image_creation.dir/build
.PHONY : range_image_creation/fast

#=============================================================================
# Target rules for targets named remove_outliers

# Build rule for target.
remove_outliers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 remove_outliers
.PHONY : remove_outliers

# fast build rule for target.
remove_outliers/fast:
	$(MAKE) -f CMakeFiles/remove_outliers.dir/build.make CMakeFiles/remove_outliers.dir/build
.PHONY : remove_outliers/fast

#=============================================================================
# Target rules for targets named statistical_removal

# Build rule for target.
statistical_removal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 statistical_removal
.PHONY : statistical_removal

# fast build rule for target.
statistical_removal/fast:
	$(MAKE) -f CMakeFiles/statistical_removal.dir/build.make CMakeFiles/statistical_removal.dir/build
.PHONY : statistical_removal/fast

#=============================================================================
# Target rules for targets named voxel_grid

# Build rule for target.
voxel_grid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voxel_grid
.PHONY : voxel_grid

# fast build rule for target.
voxel_grid/fast:
	$(MAKE) -f CMakeFiles/voxel_grid.dir/build.make CMakeFiles/voxel_grid.dir/build
.PHONY : voxel_grid/fast

src/concatenate.o: src/concatenate.cpp.o
.PHONY : src/concatenate.o

# target to build an object file
src/concatenate.cpp.o:
	$(MAKE) -f CMakeFiles/concatenate.dir/build.make CMakeFiles/concatenate.dir/src/concatenate.cpp.o
.PHONY : src/concatenate.cpp.o

src/concatenate.i: src/concatenate.cpp.i
.PHONY : src/concatenate.i

# target to preprocess a source file
src/concatenate.cpp.i:
	$(MAKE) -f CMakeFiles/concatenate.dir/build.make CMakeFiles/concatenate.dir/src/concatenate.cpp.i
.PHONY : src/concatenate.cpp.i

src/concatenate.s: src/concatenate.cpp.s
.PHONY : src/concatenate.s

# target to generate assembly for a file
src/concatenate.cpp.s:
	$(MAKE) -f CMakeFiles/concatenate.dir/build.make CMakeFiles/concatenate.dir/src/concatenate.cpp.s
.PHONY : src/concatenate.cpp.s

src/extract_indices.o: src/extract_indices.cpp.o
.PHONY : src/extract_indices.o

# target to build an object file
src/extract_indices.cpp.o:
	$(MAKE) -f CMakeFiles/extract_indices.dir/build.make CMakeFiles/extract_indices.dir/src/extract_indices.cpp.o
.PHONY : src/extract_indices.cpp.o

src/extract_indices.i: src/extract_indices.cpp.i
.PHONY : src/extract_indices.i

# target to preprocess a source file
src/extract_indices.cpp.i:
	$(MAKE) -f CMakeFiles/extract_indices.dir/build.make CMakeFiles/extract_indices.dir/src/extract_indices.cpp.i
.PHONY : src/extract_indices.cpp.i

src/extract_indices.s: src/extract_indices.cpp.s
.PHONY : src/extract_indices.s

# target to generate assembly for a file
src/extract_indices.cpp.s:
	$(MAKE) -f CMakeFiles/extract_indices.dir/build.make CMakeFiles/extract_indices.dir/src/extract_indices.cpp.s
.PHONY : src/extract_indices.cpp.s

src/kdtree_search.o: src/kdtree_search.cpp.o
.PHONY : src/kdtree_search.o

# target to build an object file
src/kdtree_search.cpp.o:
	$(MAKE) -f CMakeFiles/kdtree_search.dir/build.make CMakeFiles/kdtree_search.dir/src/kdtree_search.cpp.o
.PHONY : src/kdtree_search.cpp.o

src/kdtree_search.i: src/kdtree_search.cpp.i
.PHONY : src/kdtree_search.i

# target to preprocess a source file
src/kdtree_search.cpp.i:
	$(MAKE) -f CMakeFiles/kdtree_search.dir/build.make CMakeFiles/kdtree_search.dir/src/kdtree_search.cpp.i
.PHONY : src/kdtree_search.cpp.i

src/kdtree_search.s: src/kdtree_search.cpp.s
.PHONY : src/kdtree_search.s

# target to generate assembly for a file
src/kdtree_search.cpp.s:
	$(MAKE) -f CMakeFiles/kdtree_search.dir/build.make CMakeFiles/kdtree_search.dir/src/kdtree_search.cpp.s
.PHONY : src/kdtree_search.cpp.s

src/matrix_transform.o: src/matrix_transform.cpp.o
.PHONY : src/matrix_transform.o

# target to build an object file
src/matrix_transform.cpp.o:
	$(MAKE) -f CMakeFiles/matrix_transform.dir/build.make CMakeFiles/matrix_transform.dir/src/matrix_transform.cpp.o
.PHONY : src/matrix_transform.cpp.o

src/matrix_transform.i: src/matrix_transform.cpp.i
.PHONY : src/matrix_transform.i

# target to preprocess a source file
src/matrix_transform.cpp.i:
	$(MAKE) -f CMakeFiles/matrix_transform.dir/build.make CMakeFiles/matrix_transform.dir/src/matrix_transform.cpp.i
.PHONY : src/matrix_transform.cpp.i

src/matrix_transform.s: src/matrix_transform.cpp.s
.PHONY : src/matrix_transform.s

# target to generate assembly for a file
src/matrix_transform.cpp.s:
	$(MAKE) -f CMakeFiles/matrix_transform.dir/build.make CMakeFiles/matrix_transform.dir/src/matrix_transform.cpp.s
.PHONY : src/matrix_transform.cpp.s

src/narf_feature_extraction.o: src/narf_feature_extraction.cpp.o
.PHONY : src/narf_feature_extraction.o

# target to build an object file
src/narf_feature_extraction.cpp.o:
	$(MAKE) -f CMakeFiles/narf_feature_extraction.dir/build.make CMakeFiles/narf_feature_extraction.dir/src/narf_feature_extraction.cpp.o
.PHONY : src/narf_feature_extraction.cpp.o

src/narf_feature_extraction.i: src/narf_feature_extraction.cpp.i
.PHONY : src/narf_feature_extraction.i

# target to preprocess a source file
src/narf_feature_extraction.cpp.i:
	$(MAKE) -f CMakeFiles/narf_feature_extraction.dir/build.make CMakeFiles/narf_feature_extraction.dir/src/narf_feature_extraction.cpp.i
.PHONY : src/narf_feature_extraction.cpp.i

src/narf_feature_extraction.s: src/narf_feature_extraction.cpp.s
.PHONY : src/narf_feature_extraction.s

# target to generate assembly for a file
src/narf_feature_extraction.cpp.s:
	$(MAKE) -f CMakeFiles/narf_feature_extraction.dir/build.make CMakeFiles/narf_feature_extraction.dir/src/narf_feature_extraction.cpp.s
.PHONY : src/narf_feature_extraction.cpp.s

src/normalestimation_using_integral_image.o: src/normalestimation_using_integral_image.cpp.o
.PHONY : src/normalestimation_using_integral_image.o

# target to build an object file
src/normalestimation_using_integral_image.cpp.o:
	$(MAKE) -f CMakeFiles/normal_estimation.dir/build.make CMakeFiles/normal_estimation.dir/src/normalestimation_using_integral_image.cpp.o
.PHONY : src/normalestimation_using_integral_image.cpp.o

src/normalestimation_using_integral_image.i: src/normalestimation_using_integral_image.cpp.i
.PHONY : src/normalestimation_using_integral_image.i

# target to preprocess a source file
src/normalestimation_using_integral_image.cpp.i:
	$(MAKE) -f CMakeFiles/normal_estimation.dir/build.make CMakeFiles/normal_estimation.dir/src/normalestimation_using_integral_image.cpp.i
.PHONY : src/normalestimation_using_integral_image.cpp.i

src/normalestimation_using_integral_image.s: src/normalestimation_using_integral_image.cpp.s
.PHONY : src/normalestimation_using_integral_image.s

# target to generate assembly for a file
src/normalestimation_using_integral_image.cpp.s:
	$(MAKE) -f CMakeFiles/normal_estimation.dir/build.make CMakeFiles/normal_estimation.dir/src/normalestimation_using_integral_image.cpp.s
.PHONY : src/normalestimation_using_integral_image.cpp.s

src/octree_change_detection.o: src/octree_change_detection.cpp.o
.PHONY : src/octree_change_detection.o

# target to build an object file
src/octree_change_detection.cpp.o:
	$(MAKE) -f CMakeFiles/octree_change_detection.dir/build.make CMakeFiles/octree_change_detection.dir/src/octree_change_detection.cpp.o
.PHONY : src/octree_change_detection.cpp.o

src/octree_change_detection.i: src/octree_change_detection.cpp.i
.PHONY : src/octree_change_detection.i

# target to preprocess a source file
src/octree_change_detection.cpp.i:
	$(MAKE) -f CMakeFiles/octree_change_detection.dir/build.make CMakeFiles/octree_change_detection.dir/src/octree_change_detection.cpp.i
.PHONY : src/octree_change_detection.cpp.i

src/octree_change_detection.s: src/octree_change_detection.cpp.s
.PHONY : src/octree_change_detection.s

# target to generate assembly for a file
src/octree_change_detection.cpp.s:
	$(MAKE) -f CMakeFiles/octree_change_detection.dir/build.make CMakeFiles/octree_change_detection.dir/src/octree_change_detection.cpp.s
.PHONY : src/octree_change_detection.cpp.s

src/octree_search.o: src/octree_search.cpp.o
.PHONY : src/octree_search.o

# target to build an object file
src/octree_search.cpp.o:
	$(MAKE) -f CMakeFiles/octree_search.dir/build.make CMakeFiles/octree_search.dir/src/octree_search.cpp.o
.PHONY : src/octree_search.cpp.o

src/octree_search.i: src/octree_search.cpp.i
.PHONY : src/octree_search.i

# target to preprocess a source file
src/octree_search.cpp.i:
	$(MAKE) -f CMakeFiles/octree_search.dir/build.make CMakeFiles/octree_search.dir/src/octree_search.cpp.i
.PHONY : src/octree_search.cpp.i

src/octree_search.s: src/octree_search.cpp.s
.PHONY : src/octree_search.s

# target to generate assembly for a file
src/octree_search.cpp.s:
	$(MAKE) -f CMakeFiles/octree_search.dir/build.make CMakeFiles/octree_search.dir/src/octree_search.cpp.s
.PHONY : src/octree_search.cpp.s

src/passthrough.o: src/passthrough.cpp.o
.PHONY : src/passthrough.o

# target to build an object file
src/passthrough.cpp.o:
	$(MAKE) -f CMakeFiles/passthrough.dir/build.make CMakeFiles/passthrough.dir/src/passthrough.cpp.o
.PHONY : src/passthrough.cpp.o

src/passthrough.i: src/passthrough.cpp.i
.PHONY : src/passthrough.i

# target to preprocess a source file
src/passthrough.cpp.i:
	$(MAKE) -f CMakeFiles/passthrough.dir/build.make CMakeFiles/passthrough.dir/src/passthrough.cpp.i
.PHONY : src/passthrough.cpp.i

src/passthrough.s: src/passthrough.cpp.s
.PHONY : src/passthrough.s

# target to generate assembly for a file
src/passthrough.cpp.s:
	$(MAKE) -f CMakeFiles/passthrough.dir/build.make CMakeFiles/passthrough.dir/src/passthrough.cpp.s
.PHONY : src/passthrough.cpp.s

src/pcd_write.o: src/pcd_write.cpp.o
.PHONY : src/pcd_write.o

# target to build an object file
src/pcd_write.cpp.o:
	$(MAKE) -f CMakeFiles/pcd_write.dir/build.make CMakeFiles/pcd_write.dir/src/pcd_write.cpp.o
.PHONY : src/pcd_write.cpp.o

src/pcd_write.i: src/pcd_write.cpp.i
.PHONY : src/pcd_write.i

# target to preprocess a source file
src/pcd_write.cpp.i:
	$(MAKE) -f CMakeFiles/pcd_write.dir/build.make CMakeFiles/pcd_write.dir/src/pcd_write.cpp.i
.PHONY : src/pcd_write.cpp.i

src/pcd_write.s: src/pcd_write.cpp.s
.PHONY : src/pcd_write.s

# target to generate assembly for a file
src/pcd_write.cpp.s:
	$(MAKE) -f CMakeFiles/pcd_write.dir/build.make CMakeFiles/pcd_write.dir/src/pcd_write.cpp.s
.PHONY : src/pcd_write.cpp.s

src/project_inliers.o: src/project_inliers.cpp.o
.PHONY : src/project_inliers.o

# target to build an object file
src/project_inliers.cpp.o:
	$(MAKE) -f CMakeFiles/project_inliers.dir/build.make CMakeFiles/project_inliers.dir/src/project_inliers.cpp.o
.PHONY : src/project_inliers.cpp.o

src/project_inliers.i: src/project_inliers.cpp.i
.PHONY : src/project_inliers.i

# target to preprocess a source file
src/project_inliers.cpp.i:
	$(MAKE) -f CMakeFiles/project_inliers.dir/build.make CMakeFiles/project_inliers.dir/src/project_inliers.cpp.i
.PHONY : src/project_inliers.cpp.i

src/project_inliers.s: src/project_inliers.cpp.s
.PHONY : src/project_inliers.s

# target to generate assembly for a file
src/project_inliers.cpp.s:
	$(MAKE) -f CMakeFiles/project_inliers.dir/build.make CMakeFiles/project_inliers.dir/src/project_inliers.cpp.s
.PHONY : src/project_inliers.cpp.s

src/range_image_creation.o: src/range_image_creation.cpp.o
.PHONY : src/range_image_creation.o

# target to build an object file
src/range_image_creation.cpp.o:
	$(MAKE) -f CMakeFiles/range_image_creation.dir/build.make CMakeFiles/range_image_creation.dir/src/range_image_creation.cpp.o
.PHONY : src/range_image_creation.cpp.o

src/range_image_creation.i: src/range_image_creation.cpp.i
.PHONY : src/range_image_creation.i

# target to preprocess a source file
src/range_image_creation.cpp.i:
	$(MAKE) -f CMakeFiles/range_image_creation.dir/build.make CMakeFiles/range_image_creation.dir/src/range_image_creation.cpp.i
.PHONY : src/range_image_creation.cpp.i

src/range_image_creation.s: src/range_image_creation.cpp.s
.PHONY : src/range_image_creation.s

# target to generate assembly for a file
src/range_image_creation.cpp.s:
	$(MAKE) -f CMakeFiles/range_image_creation.dir/build.make CMakeFiles/range_image_creation.dir/src/range_image_creation.cpp.s
.PHONY : src/range_image_creation.cpp.s

src/remove_outliers.o: src/remove_outliers.cpp.o
.PHONY : src/remove_outliers.o

# target to build an object file
src/remove_outliers.cpp.o:
	$(MAKE) -f CMakeFiles/remove_outliers.dir/build.make CMakeFiles/remove_outliers.dir/src/remove_outliers.cpp.o
.PHONY : src/remove_outliers.cpp.o

src/remove_outliers.i: src/remove_outliers.cpp.i
.PHONY : src/remove_outliers.i

# target to preprocess a source file
src/remove_outliers.cpp.i:
	$(MAKE) -f CMakeFiles/remove_outliers.dir/build.make CMakeFiles/remove_outliers.dir/src/remove_outliers.cpp.i
.PHONY : src/remove_outliers.cpp.i

src/remove_outliers.s: src/remove_outliers.cpp.s
.PHONY : src/remove_outliers.s

# target to generate assembly for a file
src/remove_outliers.cpp.s:
	$(MAKE) -f CMakeFiles/remove_outliers.dir/build.make CMakeFiles/remove_outliers.dir/src/remove_outliers.cpp.s
.PHONY : src/remove_outliers.cpp.s

src/statistical_removal.o: src/statistical_removal.cpp.o
.PHONY : src/statistical_removal.o

# target to build an object file
src/statistical_removal.cpp.o:
	$(MAKE) -f CMakeFiles/statistical_removal.dir/build.make CMakeFiles/statistical_removal.dir/src/statistical_removal.cpp.o
.PHONY : src/statistical_removal.cpp.o

src/statistical_removal.i: src/statistical_removal.cpp.i
.PHONY : src/statistical_removal.i

# target to preprocess a source file
src/statistical_removal.cpp.i:
	$(MAKE) -f CMakeFiles/statistical_removal.dir/build.make CMakeFiles/statistical_removal.dir/src/statistical_removal.cpp.i
.PHONY : src/statistical_removal.cpp.i

src/statistical_removal.s: src/statistical_removal.cpp.s
.PHONY : src/statistical_removal.s

# target to generate assembly for a file
src/statistical_removal.cpp.s:
	$(MAKE) -f CMakeFiles/statistical_removal.dir/build.make CMakeFiles/statistical_removal.dir/src/statistical_removal.cpp.s
.PHONY : src/statistical_removal.cpp.s

src/voxel_grid.o: src/voxel_grid.cpp.o
.PHONY : src/voxel_grid.o

# target to build an object file
src/voxel_grid.cpp.o:
	$(MAKE) -f CMakeFiles/voxel_grid.dir/build.make CMakeFiles/voxel_grid.dir/src/voxel_grid.cpp.o
.PHONY : src/voxel_grid.cpp.o

src/voxel_grid.i: src/voxel_grid.cpp.i
.PHONY : src/voxel_grid.i

# target to preprocess a source file
src/voxel_grid.cpp.i:
	$(MAKE) -f CMakeFiles/voxel_grid.dir/build.make CMakeFiles/voxel_grid.dir/src/voxel_grid.cpp.i
.PHONY : src/voxel_grid.cpp.i

src/voxel_grid.s: src/voxel_grid.cpp.s
.PHONY : src/voxel_grid.s

# target to generate assembly for a file
src/voxel_grid.cpp.s:
	$(MAKE) -f CMakeFiles/voxel_grid.dir/build.make CMakeFiles/voxel_grid.dir/src/voxel_grid.cpp.s
.PHONY : src/voxel_grid.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... concatenate"
	@echo "... edit_cache"
	@echo "... extract_indices"
	@echo "... kdtree_search"
	@echo "... matrix_transform"
	@echo "... narf_feature_extraction"
	@echo "... normal_estimation"
	@echo "... octree_change_detection"
	@echo "... octree_search"
	@echo "... passthrough"
	@echo "... pcd_write"
	@echo "... project_inliers"
	@echo "... range_image_creation"
	@echo "... rebuild_cache"
	@echo "... remove_outliers"
	@echo "... statistical_removal"
	@echo "... voxel_grid"
	@echo "... src/concatenate.o"
	@echo "... src/concatenate.i"
	@echo "... src/concatenate.s"
	@echo "... src/extract_indices.o"
	@echo "... src/extract_indices.i"
	@echo "... src/extract_indices.s"
	@echo "... src/kdtree_search.o"
	@echo "... src/kdtree_search.i"
	@echo "... src/kdtree_search.s"
	@echo "... src/matrix_transform.o"
	@echo "... src/matrix_transform.i"
	@echo "... src/matrix_transform.s"
	@echo "... src/narf_feature_extraction.o"
	@echo "... src/narf_feature_extraction.i"
	@echo "... src/narf_feature_extraction.s"
	@echo "... src/normalestimation_using_integral_image.o"
	@echo "... src/normalestimation_using_integral_image.i"
	@echo "... src/normalestimation_using_integral_image.s"
	@echo "... src/octree_change_detection.o"
	@echo "... src/octree_change_detection.i"
	@echo "... src/octree_change_detection.s"
	@echo "... src/octree_search.o"
	@echo "... src/octree_search.i"
	@echo "... src/octree_search.s"
	@echo "... src/passthrough.o"
	@echo "... src/passthrough.i"
	@echo "... src/passthrough.s"
	@echo "... src/pcd_write.o"
	@echo "... src/pcd_write.i"
	@echo "... src/pcd_write.s"
	@echo "... src/project_inliers.o"
	@echo "... src/project_inliers.i"
	@echo "... src/project_inliers.s"
	@echo "... src/range_image_creation.o"
	@echo "... src/range_image_creation.i"
	@echo "... src/range_image_creation.s"
	@echo "... src/remove_outliers.o"
	@echo "... src/remove_outliers.i"
	@echo "... src/remove_outliers.s"
	@echo "... src/statistical_removal.o"
	@echo "... src/statistical_removal.i"
	@echo "... src/statistical_removal.s"
	@echo "... src/voxel_grid.o"
	@echo "... src/voxel_grid.i"
	@echo "... src/voxel_grid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

